# This workflow will launch at 00:00 every Saturday
on:
  schedule:
    - cron: '0 0 * * 6'
  workflow_dispatch:

jobs:
  scala-steward:
    name: Launch Scala Steward
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Generate token
        id: generate_token
        uses: tibdex/github-app-token@v1.3
        with:
          app_id: ${{ secrets.SCALA_STEWARD_APP_ID }}
          private_key: ${{ secrets.SCALA_STEWARD_APP_PRIVATE_KEY }}

      - name: Launch Scala Steward
        uses: scala-steward-org/scala-steward-action@v2
        with:
          github-token: ${{ steps.generate_token.outputs.token }}
          author-email: 5388508+xirc@users.noreply.github.com
          repos-file: repos.md